#!/bin/bash

record_file='dump1'
begin=$1
end=$2

cat $record_file | sed -n "/$begin/,/$end/ {s/^.\+length \(.\+\)$/\1/p;s/^.\+(\([0-9]\+\))$/\1/p}" | tr '\n' '+' | xargs -l  bash -c 'echo $(($0 + 0))'

