#!/bin/bash

ip=$1
metric=$2
hold_time=$3
N=$4
mibs="hrSWRunName $metric"


while true
do
	topNSW=`snmpwalk -v2c -c public $ip $metric | sort -k4 -nr | sed 's/^.\+\.\([0-9]\+\).\+$/\1/' | head -$N`
	i=0
	for idx in $topNSW
	do
		o=$i
		o+=' '
		i=$(($i+1))

		for met in $mibs
		do
			o+=`snmpget -Oqv -v2c -c public $ip $met.$idx`
			o+=' '
		done
		echo $o
	done
	sleep $hold_time
	clear
done
