#!/bin/bash

ip=$1
mibs=$2
hold_time=$3


prev=`snmpget -Oqv -v2c -c public $ip $mibs`

while true; do
	curr=`snmpget -Oqv -v2c -c public $ip $mibs`
	echo $(( $curr - $prev ))
	prev=$curr
	sleep $hold_time
done
